#!/usr/bin/env python3
from pathlib import Path
import argparse

job_dir = Path() / 'job_dir'
assert job_dir.exists(), f"Job dir {job_dir} does not exist"

job_dir_folders = {int(f.name.replace('.', '')): f for f in job_dir.glob('*/')}

# Grab job log id

parser = argparse.ArgumentParser()
parser.add_argument('job_id', type=int, nargs='?', default=None)
args = parser.parse_args()

if args.job_id is None:
    print("Job ids:")
    print(sorted(job_dir_folders.keys()))
    exit(0)

job_id = args.job_id
assert job_id in job_dir_folders, f"Job id {job_id} does not exist"

job_folder = job_dir_folders[job_id]

# load stdout and stderr
stdout_file = job_folder / 'job.out'
stderr_file = job_folder / 'job.err'

assert stdout_file.exists(), f"Stdout file {stdout_file} does not exist"
assert stderr_file.exists(), f"Stderr file {stderr_file} does not exist"

with open(stdout_file, 'r') as f:
    stdout = f.readlines()

with open(stderr_file, 'r') as f:
    stderr = f.readlines()

print(f"Stdout for job {job_id}:")
print(''.join(stdout))
print(f"Stderr for job {job_id}:")
print(''.join(stderr))
